# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.os }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.os }}
        cache: 'npm'
        cache-dependency-path: 'server/package-lock.json'
    - run: npm install
      working-directory: server
    - run: npm ci
      working-directory: server
    - run: npm run build --if-present
      working-directory: server
    - run: npm test
      working-directory: server

  
