name: Chrome
on: push
jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4

      # Add a step to install dependencies and generate lockfile
      - name: Install Dependencies
        run: |
          npm install
          # or yarn install if you're using Yarn

      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
