name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      DB_HOST: studmysql01.fhict.local

      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_database
        ports:
          - 5000:5000 # Adjust the port to match your server port

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Navigate to the client directory
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      # Install dependencies for client
      - name: Install dependencies for client
        run: |
          cd client
          npm install

      # Build client
      - name: Build client
        run: |
          cd client
          npm run build

      # Start server
      - name: Start server
        run: |
          cd server
          npm install
          npm run dev

      # Start client
      - name: Start client
        run: |
          cd client
          npm start

      # Wait for both server and client to be ready
      - name: Wait for server and client
        run: npx wait-on http://127.0.0.1:5000 http://127.0.0.1:3000

      # Run Cypress tests
      - name: Run Cypress tests
        run: |
          cd client
          npx cypress run --browser chrome
