name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Navigate to the client directory
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          cd client
          npm install
          cd server
          npm install

      # Build the application
      - name: Build application
        run: |
          cd client
          npm run build

      # Run Cypress tests
      - name: Start application
        run: |
          cd client
          npm start & npx wait-on http://127.0.0.1:3000
      
      - name: Build server
        run: |
          cd server
          npm run build

      # Run Cypress tests
      - name: Start server
        run: |
          cd server
          npm run dev & npx wait-on http://127.0.0.1:5000
      
          
      - name: Run Cypress tests
        run: |
          cd client
          npx cypress run --browser chrome
