name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies for client and server
        run: |
          cd client
          npm install
          cd ../server
          npm install

      - name: Build client
        run: |
          cd client
          npm run build

      - name: Start server and client in the foreground
        run: |
          cd server
          npm run dev &
          npx wait-on http://127.0.0.1:5000
          echo "Server is ready. Proceeding to start client."
          
          
      - name: Start client in the foreground
        run: |
          cd ../client
          npm start &
          npx wait-on http://127.0.0.1:3000
          

      - name: Run Cypress tests
        run: |
          cd client
          npx cypress run --browser chrome
