name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Navigate to the client directory
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'
  
      # Install dependencies and run Cypress tests
      - name: Install dependencies and run Cypress
        run: |
          npm install
          npm run build
          npm start
          npx cypress run
        working-directory: client
